image:
  repository: similarweb/statusbay
  tag: 0.1.0
  pullPolicy: IfNotPresent

database:
  type: internal

  host: 127.0.0.1 # Redundent if using internal
  port: 3306 # Redundent if using internal
  username: statusbay
  password: changeme
  schema: statusbay

  internal:
    image:
      repository: mysql
      tag: 5.7
      pullPolicy: IfNotPresent
    resources:
     requests:
       memory: 256Mi
       cpu: 100m
    persistence:
      persistentVolumeClaim:      
        accessMode: ReadWriteOnce
        storageClass: "-" 
        size: 1Gi

ingress:
  api:
    annotations: {}
    host: api.statusbay.domain
  ui:
    annotations: {}
    host: statusbay.domain

service:
  api:
    type: ClusterIP
    annotations: {}
    externalPort: 80
  ui:
    type: ClusterIP
    annotations: {}
    externalPort: 80    

rbac:
  create: true

serviceAccount:
  create: true
  name: 

ui:
  create: true
  replicas: 2
  annotations: {}
  
  image:
    repository: similarweb/statusbay-ui
    tag: 0.1.0
    pullPolicy: IfNotPresent
  
  # environmentVars is a list of  enviroment variables to set with the UI deployment. These could be
  # used to set API_URL ,GELF ADDRESS & LOG_LEVEL.
  environmentVars:
    API_URL: "statusbay-api"
    GELF_ADDRESS: 127.0.0.1
    LOG_LEVEL: INFO
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

api:
  create: true
  replicas: 2
  annotations: {}
  application:    
    log:
      level: INFO
      # gelf_address: 127.0.0.1
    metrics:
      # datadog:
      #   api_key: example-api-key
      #   app_key: example-app-key
      #   cache_cleanup_interval: 1m
      #   cache_expiration: 3m
      # prometheus:
      #   address: http://prometheus-url.domain:9090
    alerts:
      # statuscake:
      #   endpoint: https://app.statuscake.com/API
      #   username: example-username
      #   api_key: example-api-key
      # pingdom:
      #   endpoint: https://api.pingdom.com/api
      #   token: example-token
    events:
      pod:
      - pattern: "Readiness probe failed"
        descriptions:
          - >-
            The pod not pass the hatcheck:
            <ul>
              <li>Indicates whether the Container is ready to service requests. If the readiness probe fails, the endpoints controller removes the Pod’s IP address from the endpoints of all Services that match the Pod. </li>
              <li><a href="https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate" target="_blank">Read more on Readiness details</a></li>
            </ul>
      - pattern: "OOMKilled"
        descriptions:
          - >-
            Whether this container has been killed because it ran out of memory.:
            <ul>
              <li><TODO.../li>
            </ul>
      - pattern: "ExitCode"
        descriptions:
          - >-
            The last exit code of this container.:
            <ul>
              <li>TODO..</li>
            </ul>
      - pattern: "CrashLoopBackOff"
        descriptions:
        - >-
          TBD
          <ul>
              <li>TODO....</li>
          </ul>
      replicaset:
      - pattern: "Replicaset event example"
        descriptions:
        - >-
          TBD
          <ul>
              <li>TODO....</li>
          </ul>
      deployment:
      - pattern: "Deployment event example"
        descriptions:
        - >-
          TBD
          <ul>
              <li>TODO....</li>
          </ul>
      demonset:
      - pattern: "Demonset event example"
        descriptions:
        - >-
          TBD
          <ul>
              <li>TODO....</li>
          </ul>
      statefulset:
      - pattern: "Statefulset event example"
        descriptions:
        - >-
          TBD
          <ul>
              <li>TODO....</li>
          </ul>
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

watcher:
  kubernetes:
    create: true
    annotations: {}
    application:
      cluster_name: default
      log:
        level: INFO
        # gelf_address: 127.0.0.1
      ui:
        base_url: todo
      applies:
        save_interval: 2s
        max_apply_time: 10m
        check_finish_delay: 5s
        collect_data_after_apply_finish: 10s
      # slack:
      #   token: example-slack-token
      #   default_channels:
      #     - "#example-channel"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi



