image:
  repository: similarweb/statusbay
  tag: dev
  pullPolicy: Always

database:
  type: internal

  host: 127.0.0.1 # Redundent if using internal
  port: 3306 # Redundent if using internal
  username: statusbay
  password: changeme
  schema: statusbay

  internal:
    image:
      repository: mysql
      tag: 5.7
      pullPolicy: Always
    resources:
     requests:
       memory: 256Mi
       cpu: 100m
    persistence:
      persistentVolumeClaim:      
        accessMode: ReadWriteOnce
        storageClass: "-" 
        size: 1Gi

ingress:
  api:
    annotations: {}
    host: api.statusbay.domain
  ui:
    annotations: {}
    host: statusbay.domain

service:
  api:
    type: ClusterIP
    annotations: {}
    externalPort: 80
  ui:
    type: ClusterIP
    annotations: {}
    externalPort: 80    

rbac:
  create: true

serviceAccount:
  create: true
  name: 

ui:
  create: true
  replicas: 2
  annotations: {}
  
  image:
    repository: similarweb/statusbay-ui
    tag: dev
    pullPolicy: Always
  
  application:
    log:
      level: INFO
      # gelf_address: 127.0.0.1
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

api:
  create: true
  replicas: 2
  annotations: {}
  application:    
    log:
      level: INFO
      # gelf_address: 127.0.0.1
    metrics:
      # datadog:
      #   api_key: example-api-key
      #   app_key: example-app-key
      #   cache_cleanup_interval: 1m
      #   cache_expiration: 3m
      # prometheus:
      #   address: http://prometheus-url.domain:9090
    alerts:
      # statuscake:
      #   endpoint: https://app.statuscake.com/API
      #   username: example-username
      #   api_key: example-api-key
      # pingdom:
      #   endpoint: https://api.pingdom.com/api
      #   token: example-token
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

watcher:
  kubernetes:
    create: true
    annotations: {}
    application:
      cluster_name: default
      log:
        level: INFO
        # gelf_address: 127.0.0.1
      ui:
        base_url: todo
      applies:
        save_interval: 2s
        max_apply_time: 10m
        check_finish_delay: 5s
        collect_data_after_apply_finish: 10s
      # slack:
      #   token: example-slack-token
      #   default_channels:
      #     - "#example-channel"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi



