{{- if .Values.watcher.kubernetes.create  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statusbay.fullname" . }}-configmap-watcher-kubernetes
  labels:
{{ include "statusbay.labels" . | indent 4 }}
data: 
  config: |-
    ---
    cluster_name: {{ toYaml .Values.watcher.kubernetes.application.cluster_name }}
    log:
      {{- toYaml  .Values.watcher.kubernetes.application.log | nindent 6 }}
    mysql:
      dns: "{{ template "statusbay.database.host" . }}"
      port: {{ template "statusbay.database.port" . }}
      username: "{{ template "statusbay.database.username" . }}"
      password: "{{ template "statusbay.database.rawPassword" . }}"
      schema: "{{ template "statusbay.database.schema" . }}"
    slack:
      {{- toYaml .Values.watcher.kubernetes.application.slack | nindent 6 }}
    ui:
      {{- toYaml .Values.watcher.kubernetes.application.ui | nindent 6 }}
    applies:
      {{- toYaml .Values.watcher.kubernetes.application.applies | nindent 6 }}
{{- end -}}