{{- if and (.Values.rbac.create) (.Values.watcher.kubernetes.create)  }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "statusbay.fullname" . }}
  labels:
{{ include "statusbay.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "statusbay.fullname" . }}-readonly
subjects:
  - kind: ServiceAccount
    name: {{ template "statusbay.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end -}}