{{- if (eq .Values.redis.type "internal") }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "statusbay.redis" . }}"
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{ include "statusbay.annotations" . | indent 4 }}
spec:
  selector:
{{ include "statusbay.matchLabels" . | indent 4 }}
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end -}}
