{{- if .Values.ui.create  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "statusbay.fullname" . }}-ui
  labels:
{{ include "statusbay.labels" . | indent 4 }}
    component: {{ include "statusbay.fullname" . }}-ui
  annotations:
{{ toYaml .Values.ui.annotations | indent 4}}
spec:
  selector:
    matchLabels:
{{ include "statusbay.matchLabels" . | indent 6 }}
      component: {{ include "statusbay.fullname" . }}-ui
  replicas: {{ .Values.ui.replicas }}
  template:
    metadata:
      labels:
{{ include "statusbay.labels" . | indent 8 }}
        component: {{ include "statusbay.fullname" . }}-ui
    spec:
      serviceAccountName: {{ template "statusbay.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            - name: API_URL
              value: "http://{{ template "statusbay.fullname" . }}-api/api/v1/kubernetes"
            - name: GELF_ADDRESS
              value: "{{ toYaml  .Values.ui.application.log.gelf_address | nindent 12 }}"
            - name: LOG_LEVEL
              value: "{{ toYaml  .Values.ui.application.log.level | nindent 12 }}"
{{- end -}}