{{- if .Values.api.create  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statusbay.fullname" . }}-configmap-api
  labels:
{{ include "statusbay.labels" . | indent 4 }}
data: 
  config: |-
    ---
    log:
      {{- toYaml .Values.api.application.log | nindent 6 }}
    mysql:
      dns: "{{ template "statusbay.database.host" . }}"
      port: {{ template "statusbay.database.port" . }}
      username: "{{ template "statusbay.database.username" . }}"
      password: "{{ template "statusbay.database.rawPassword" . }}"
      schema: "{{ template "statusbay.database.schema" . }}"
    metrics:
      {{- toYaml .Values.api.application.metrics | nindent 6 }}
    alerts:
      {{- toYaml .Values.api.application.alerts | nindent 6 }}

  events: |-
    ---
    pod:
    - pattern: "Readiness probe failed"
      descriptions:
        - >-
          The pod not pass the hatcheck:
          <ul>
            <li>Indicates whether the Container is ready to service requests. If the readiness probe fails, the endpoints controller removes the Pod’s IP address from the endpoints of all Services that match the Pod. </li>
            <li><a href="https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate" target="_blank">Read more on Readiness details</a></li>
          </ul>
    - pattern: "OOMKilled"
      descriptions:
        - >-
          Whether this container has been killed because it ran out of memory.:
          <ul>
            <li><TODO.../li>
          </ul>
    - pattern: "ExitCode"
      descriptions:
        - >-
          The last exit code of this container.:
          <ul>
            <li>TODO..</li>
          </ul>
    - pattern: "CrashLoopBackOff"
      descriptions:
      - >-
        TBD
        <ul>
            <li>TODO....</li>
        </ul>
    - pattern: "Error: ErrImagePull"
      descriptions:
        - >-
          Error occurred during image pulling.
          <ul>
            <li>Check the repository, image name and tag are valid</li>
            <li>Verify that image exists in the registry</li>
            <li>Verify the host is authorized to download that image</li>
            <li>Check connectivity from the host to the registry</li>
          </ul>
    replicaset:
    - pattern: "Replicaset event example"
      descriptions:
      - >-
        TBD
        <ul>
            <li>TODO....</li>
        </ul>
    deployment:
    - pattern: "Deployment event example"
      descriptions:
      - >-
        TBD
        <ul>
            <li>TODO....</li>
        </ul>
    demonset:
    - pattern: "Demonset event example"
      descriptions:
      - >-
        TBD
        <ul>
            <li>TODO....</li>
        </ul>
    statefulset:
    - pattern: "Statefulset event example"
      descriptions:
      - >-
        TBD
        <ul>
            <li>TODO....</li>
        </ul>
{{- end -}}
