{{- if .Values.api.create  -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "statusbay.fullname" . }}-api
  labels:
{{ include "statusbay.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
{{ include "statusbay.matchLabels" . | indent 4 }}
    component: {{ include "statusbay.fullname" . }}-api
  type: {{ .Values.service.api.type }}
  ports:
  - port: {{ .Values.service.api.externalPort }}
    targetPort: 8080
    name: "http"
{{- end -}}